version: "3.10"

services:
  redis:
    image: redis:latest

  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgresql

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A stores worker -l info -E
    depends_on:
      - redis
      - postgresql

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A stores beat -l info
    depends_on:
      - redis
      - postgresql

volumes:
  postgres_data:
