# Generated by Django 3.0.5 on 2023-02-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storestatus',
            name='timestamp_utc',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='businesshour',
            unique_together={('store', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='storestatus',
            unique_together={('store', 'timestamp_utc')},
        ),
    ]
