# Generated by Django 3.0.5 on 2023-02-22 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
        migrations.RemoveField(
            model_name='store',
            name='name',
        ),
    ]
