# Generated by Django 3.1.6 on 2023-02-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_altered_meta_in_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereport',
            name='downtime_last_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='downtime_last_hour',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='downtime_last_week',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='uptime_last_day',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='uptime_last_hour',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='uptime_last_week',
            field=models.FloatField(),
        ),
    ]
